### ISSUE TITLE
Add simple, title-based filtering of topics and units

### ISSUE THREAD

**Issue by bsenyk** [iilab/openmentoring-mobile#35]

**Comment by jmatsushita** [comment]
Just reviewed this and it works well! Two things to look at next:
 1/ Display only the units that are results of the search (and the parent topic)
 2/ Disable the Pull to Refresh in the search view.

Thanks!

**Comment by bsenyk** [comment]
@jmatsushita Both make sense to me.  I've disabled Pull to Refresh in the most complete way without destroying the view and re-rendering all of it.  It still allows the user to pull down, but returns immediately.  Play with it and let me know what you think.

I'm still working on 1/
