### ISSUE TITLE
Search window glitch

### ISSUE THREAD

**Issue by dealson4ne** [iilab/openmentoring-mobile#46]
# SUMMARY

On which screen were you BEFORE the problem occurred?
... Home window
Which ACTION did you do that led to the problem?
... I tapped the search button on the upper right corner of the home/Topic window and searched for  "chat" where I got some options below. 
I selected my desired option from the displayed. 
What PROBLEM happened?
...in the unit window I had selected, the search bar above the window remained and with even the optional buttons on the search bar, it could not respond. 
It's irritating that it remains hanging on the page and as well can be gotten rid of.
What did you EXPECT instead?
...1. I would expect the back button on the left of the search bar to respond by making the bar disappear.
2. I would expect the search button on the top right of the search bar to take new search requests
# TECHNICAL DETAILS

Open Mentoring version: ...
Android version: ...
Device brand and model: ...
Any other useful information depending on context (Internet availability, Mobile provider,etc): ...

**Comment by bsenyk** [comment]
I believe this is fixed by the new search layout/filter bar.

**Comment by jmatsushita** [comment]
It is fixed in the new upcoming 0.0.4 release.
