### ISSUE TITLE
Cannot download topics on latest version (0.0.2-dev)

### ISSUE THREAD

**Issue by jmatsushita** [iilab/openmentoring-mobile#48]
# SUMMARY

On which screen were you BEFORE the problem occurred?
Topic Screen

Which ACTION did you do that led to the problem?
Click on download icon

What PROBLEM happened?
Nothing happened

What did you EXPECT instead?
For the topic (Safe Social Networking, the problem happens with all other topics) to be downloaded
# TECHNICAL DETAILS

Open Mentoring version: ...
Android version: ...
Device brand and model: ...
Any other useful information depending on context (Internet availability, Mobile provider,etc): ...

**Comment by bsenyk** [comment]
Hi @jmatsushita, is it possible that this is a slow internet connection issue? It occurred to me that we don't have a progress indicator.

**Comment by bsenyk** [comment]
Closing this issue -- cannot replicate and seems to be fixed based on other conversations.

**Comment by jmatsushita** [comment]
Indeed. Fixed in latest versions.
