### ISSUE TITLE
Differentiate icon for 'download topic' and 'update topic'

### ISSUE THREAD

**Issue by blazman** [iilab/openmentoring-mobile#50]
# SUMMARY

Please describe the feature you would like to be added? 
Differentiate icon for 'download topic' and 'update topic'. Instead of a cloud/download icon, either the word 'update' in a nice colour, or some other good icon.

Why do you think this is an important feature?
Users who have downloaded topics will be confused/frustrated that the topics they have already downloaded again have the download icon. They will have the feeling of forever downloading the same thing. Updating is more logical/positive.

**Comment by jmatsushita** [comment]
Thanks @blazman!
