### ISSUE TITLE
Pull to refresh text shows when dragging down halfway

### ISSUE THREAD

**Issue by jmatsushita** [iilab/openmentoring-mobile#53]
When dragging the topic screen a little without going up to the point where the arrow turns up, then when releasing the "Pull to Refresh..." text stays half visible under the search box.

![image](https://cloud.githubusercontent.com/assets/356097/11844424/08765636-a40f-11e5-92bc-18848575d52a.png)

**Comment by bsenyk** [comment]
In my testing, this is fixed in Ionic 1.2.1, but I could not update because of an issue with the slides component.  That issue may have been fixed in a later update, so I will try updating again in the 0.2.0 release of our app.
