### ISSUE TITLE
Close button in the settings window is too faint. How about a bold cross (x) instead!

### ISSUE THREAD

**Issue by dealson4ne** [iilab/openmentoring-mobile#63]
The faint close button on the top right corner of the settings window gives the impression that its non function and in other cases may be easily missed just in case someone to exit  without making any settings changes. 
I would like to suggest a clear bold cross (x) button instead.

**Comment by jmatsushita** [comment]
This has been replaced by a Home button. Watch out for the new release on F-Droid today or tomorrow!
