### ISSUE TITLE
Recomend: Main Subject-title to be included on top of each flash card page

### ISSUE THREAD

**Issue by dealson4ne** [iilab/openmentoring-mobile#77]
I feel it would be nice to include or add the Main subject-title on top of each flash card. 
Take an example of  main subject title to be: Dealing with Emergencies
Then the "getting stated" page would include first on top of the page in small font size   "Dealing with Emergencies"  and below, a slightly bigger font of "Getting started" and then a bigger font of "Introduction"

I would imagine with this sort of format, would help the user to fully understand or be reminded of where they are.

**Comment by jmatsushita** [comment]
Thanks for this. We have implemented this recommendation on the new version!
